### ISSUE TITLE
MQTT over SSL support

### ISSUE THREAD

**Issue by Lucide** [LightJockey/MqttDroid#1]
Hello! Is encrypted mqtt (over SSL) supported in this client?
I have a mosquitto broker.
I've tried prepending `ssl://` to the broker URL but no luck 🤔

**Comment by LightJockey** [comment]
Hi, it should be supported now.
Can you give the latest release a try and see if it works for you?

These are my mosquitto settings:
```
listener 8883
cafile ./certs/ca-root-cert.crt
certfile ./certs/server.crt
keyfile ./certs/server.key
require_certificate false
allow_anonymous true
```

Certificate was self-signed, tested with the validate setting off.

**Comment by Lucide** [comment]
Impressive! I confirm it works with verifiable certificates too. 🫡

I take the occasion to ask you some usage clarifications: it seems that the app supports some form of status detection, for example to populate the switch widget to the current value.

Tasmota-powered devices support status querying, is this relevant? Currently the widget always loads in an "off" state.

**Comment by LightJockey** [comment]
Thanks for the feedback!

As for your question, the app doesn't perform any sort of querying by itself, the toggle widget will be set on or off depending on the payload received on its sub topic.

That's all really, if you want the widget to populate with the current state, you will have to set the retained flag on the Tasmota device so that the app receives the state message as soon as it connects to the broker (https://tasmota.github.io/docs/MQTT/#retained-mqtt-messages).

Also I believe you cannot use the same topic both for issuing commands and getting status updates on Tasmotas, so that's where the separate pub/sub option comes in handy -- basically you'd have something like this: pub `cmnd/device/power`, sub `stat/device/power`.

Does that help?

**Comment by Lucide** [comment]
Thanks! You made me discover that in mqtt there's only one retained message per-channel.
I had gotten phantom retained status messages in the past when I tried this approach, but now I realize the issue must've been somewhere else between the keyboard and the chair. 😅

**Comment by LightJockey** [comment]
Some aspects of mqtt can be confusing at first, I think we've all been there at some point 😂 just make sure to only retain what's actually needed.

Tools like [mqtt-explorer](https://mqtt-explorer.com) are also of great help to discover what's still retained in the broker.

Cheers!
